spring:
  config:
    activate:
      on-profile: prod

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://172.27.0.52:3306/TEST?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Blind$242

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    logging:
      level:
        org.hibernate.SQL: debug

  # Security OAuth
  security:
    oauth2.client:
      registration:
        42:
          client-id: "ec8a6ce5eb83c2ae14f77cc3068d19eec7556d6feae19301c2b771394870c116"
          client-secret: "73fdaea19d7872e6fb1d11f46e5ff4aa763af7ea115cee0dbf1ccb52f9e4a116"

server:
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: seoul42$2
    key-store-type: PKCS12
  port: 8443