spring:
  profiles:
    active: local

  # Security OAuth
  security:
    oauth2.client:
      registration:
        42:
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          authorization-grant-type: authorization_code
          scope: public
      provider:
        42:
          authorization-uri: "https://api.intra.42.fr/oauth/authorize"
          token-uri: "https://api.intra.42.fr/oauth/token"
          user-info-uri: "https://api.intra.42.fr/v2/me"
          user-name-attribute: id

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  # pageable
  data:
    web:
      pageable:
        default-page-size: 24
        one-indexed-parameters: true

  # Swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Message 설정
  messages:
    basename: 'messages/validation'
    encoding: UTF-8



app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://42byte.kr/oauth/redirect

# jwt secret key 설정
jwt.secret: a2f6abd304bcd1d2ff9691bb0e7c1bab1010d0466c628d23b49550fb932300a43054a6030811f6118eb8129d9033cf5e2b63b762c5bd7bee246f63d34ee04fd3
