spring:
  config:
    activate:
      on-profile: local

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/TEST?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: blind42blind42

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    logging:
      level:
        org.hibernate.SQL: debug

  # Security OAuth
  security:
    oauth2.client:
      registration:
        42:
          client-id: "07036ff026b85153a047cf5188ce23a007d3e645b3293f71c4267f7c90917e04"
          client-secret: "b98634d8305b9d6a4750427bc3d6ecc403a7394916facb4947b4d9377b506bc7"
